# Generated by Django 6.1.2 on 2026-10-08 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name with Title (e.g. Dr. Jane Smith)', max_length=150)),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology'), ('Dermatology', 'Dermatology'), ('General Medicine', 'General Medicine')], default='Cardiology', max_length=50)),
                ('specialization', models.CharField(help_text='Specialization or sub-discipline', max_length=150)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=75.0, max_digits=8)),
                ('available_days', models.CharField(default='Monday, Tuesday, Wednesday, Thursday, Friday', max_length=120)),
                ('active_status', models.BooleanField(default=True, help_text='Is doctor actively taking appointments?')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('room_number', models.CharField(default='Room 201', max_length=20)),
                ('experience_years', models.PositiveIntegerField(default=8)),
                ('bio', models.TextField(blank=True, help_text='Short professional summary')),
                ('avatar_color', models.CharField(default='primary', help_text='Bootstrap theme color for avatar', max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00 AM - 09:30 AM', '09:00 AM - 09:30 AM'), ('09:30 AM - 10:00 AM', '09:30 AM - 10:00 AM'), ('10:00 AM - 10:30 AM', '10:00 AM - 10:30 AM'), ('10:30 AM - 11:00 AM', '10:30 AM - 11:00 AM'), ('11:00 AM - 11:30 AM', '11:00 AM - 11:30 AM'), ('11:30 AM - 12:00 PM', '11:30 AM - 12:00 PM'), ('02:00 PM - 02:30 PM', '02:00 PM - 02:30 PM'), ('02:30 PM - 03:00 PM', '02:30 PM - 03:00 PM'), ('03:00 PM - 03:30 PM', '03:00 PM - 03:30 PM'), ('03:30 PM - 04:00 PM', '03:30 PM - 04:00 PM'), ('04:00 PM - 04:30 PM', '04:00 PM - 04:30 PM'), ('04:30 PM - 05:00 PM', '04:30 PM - 05:00 PM')], max_length=50)),
                ('reason', models.TextField(help_text='Chief complaint or reason for visit')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from doctor or receptionist', null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital.doctor')),
            ],
            options={
                'ordering': ['-date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='Clinical findings and diagnosis')),
                ('prescription', models.TextField(help_text='Medications, dosages, and instructions')),
                ('notes', models.TextField(blank=True, help_text='Additional recovery recommendations and follow-up', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_report', to='hospital.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='hospital.patient')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital.patient'),
        ),
    ]
